server:
  port: 8080

spring:
  datasource:
    continue-on-error: false
    driverClassName: org.h2.Driver
    password: ''
    sql-script-encoding: utf-8
    url: jdbc:h2:mem:pccwexam;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  mail:
    host: smtp.localhost